services:
  pixel:
    build:
      context: .
      dockerfile: Dockerfile
    image: pixel
    container_name: pixel
    networks:
      - app_net
    env_file: .env
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '2.0'
          memory: 1G
  redis:
    image: redis:7.4
    command: ["redis-server", "--maxmemory", "2gb", "--maxmemory-policy", "allkeys-lru"]
    networks:
      - app_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 30s
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G

networks:
  app_net:
    name: app_net
    driver: bridge
